### PR TITLE
make csv file rading more flexible

### PR DESCRIPTION
**Pull request by simei94**
read_delim can automatically determine the delimiter, no need to pre-define it

### CODE REVIEW

**Comment by simei94** [comment]
@billyc is branch 0.2.1 the correct path to merge to?

**Comment by tschlenther** [comment]
> @billyc is branch 0.2.1 the correct path to merge to?

@billyc or @zlukich can you help out?

**Comment by tschlenther** [comment]
@simei94  I thikn you need to merge it into the master

**Comment by billyc** [comment]
@simei94 my apologies that this PR languished. I'm taking a look now -- the 0.2 branch has all the most recent work, that entire branch should be merged to master. 

I can do that, I think we were waiting for some reason (now lost to the fog of time)

**Review by billyc — APPROVED** [review]

**Comment by billyc** [comment]
@simei94 @tschlenther all code has been merged onto master. Do not use the 0.2.1 branch, that release is already published.

You can create future PR's from master now.

**Pull request merged**
